# Generated by Django 6.0.2 on 2026-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('area', models.CharField(choices=[('ext', 'Extrusión'), ('imp', 'Impresión'), ('con', 'Conversión')], max_length=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('maquina', models.CharField(blank=True, default='', max_length=100)),
                ('mo', models.CharField(blank=True, default='', max_length=50, verbose_name='MO #')),
                ('item', models.CharField(blank=True, default='', max_length=20, verbose_name='Ítem')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción del producto')),
                ('turno', models.CharField(choices=[('A', 'Turno A (6:00 AM - 2:00 PM)'), ('B', 'Turno B (2:00 PM - 10:00 PM)'), ('C', 'Turno C (10:00 PM - 6:00 AM)')], default='A', max_length=1)),
                ('auditor', models.CharField(blank=True, default='', max_length=100)),
                ('filas', models.PositiveIntegerField(default=0)),
                ('guardado_at', models.DateTimeField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Calidad',
                'verbose_name_plural': 'Registros de Calidad',
                'ordering': ['-guardado_at'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Auditor', 'Auditor de Calidad'), ('Supervisor', 'Supervisor'), ('Operador', 'Operador')], default='Operador', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_empleado', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('cedula', models.CharField(blank=True, default='', max_length=15)),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'ordering': ['nombre'],
            },
        ),
    ]
